<?php
// Generated by automation for Lando dev.
use Drupal\Core\Installer\InstallerKernel;


$settings['hash_salt'] = 'lando-dev-hash-salt';
$settings['config_sync_directory'] = '../config/sync';


if (InstallerKernel::installationAttempted()) {
  $settings['install_profile'] = 'standard';
}

if (file_exists($app_root . '/' . $site_path . '/settings.local.php')) {
  include $app_root . '/' . $site_path . '/settings.local.php';
}
